### ISSUE TITLE
todo before going public

### ISSUE THREAD

**Issue by HugoLhuillier** [HugoLhuillier/TwoAssetsContinuousTime#1]
- [x] allow for more than two income states 
- [x] solve the kolmogorov forward equation 
- [ ] implement parallelization (will help a bit, but most of the computation is in the solver, which is already parallelized via Pardiso.jl)
- [x] update README.md with Pardiso.jl dependency for faster branch

**Comment by HugoLhuillier** [comment]
forgot to mention, but 

- 37b8590a8eecaf848e9bd05aa50e1fb14aa76ae3 includes more than two income state levels 
- e12c4036c84cedfb42343b0520a2def88b383dd1 replaces the idrs solver by the pardiso one which implements parallel computing 
- 5d89b90e2e7112b3e82e96fd1cf321737956fa44 updates the readme.md with the pardiso.jl dependency

**Comment by HugoLhuillier** [comment]
parallel computing has been merged with #2. closing.
